export interface INavItem {
  label: string
  href: string
}

export interface IPortfolioItem {
  title: string
  desc: string
  img: string
  link: string
}

export interface IPost {
  content: string // Generated by gray-matter
  slug: string
  title: string
  desc: string
  tags: string[]
  publishedAt: string
  img: string
  imgAlt: string
}
