import type { Metadata } from 'next'
import { Navbar, Footer } from '@/components'
import '@/assets/main.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-svh flex flex-col p-3 md:p-5 lg:p-7">
          <div className="grow bg-background border rounded shadow-md w-full lg:max-w-screen-xl lg:mx-auto flex flex-col">
            <Navbar />
            <div className="grow flex flex-col size-full">
              {children}
            </div>
            <Footer />
          </div>
        </main>
      </body>
    </html>
  )
}
